### ISSUE TITLE
Alpine error minizip

### ISSUE THREAD

**Issue by sodomon2** [cizra/darkmod_src#1]
Here's the mistake.

-IThirdParty/artefacts/pugixml/include -Irenderer -I. -Iidlib -Iframework -Igame framework/FileSystem.cpp
framework/File.cpp:21:10: fatal error: unzip.h: No such file or directory
 #include "unzip.h"
          ^~~~~~~~~
compilation terminated.
scons: *** [build/scons_x64/release/core/framework/File.o] Error 1
framework/FileSystem.cpp:21:10: fatal error: unzip.h: No such file or directory
 #include "unzip.h"
          ^~~~~~~~~
compilation terminated.
scons: *** [build/scons_x64/release/core/framework/FileSystem.o] Error 1
scons: building terminated because of errors.

**Comment by sodomon2** [comment]
I cloned the svn version but now I get another error here the error

tools/compilers/roqvq/codec.cpp: In member function 'int codec::BestCodeword(unsigned char*, int, double**)':
tools/compilers/roqvq/codec.cpp:22:29: error: '_HUGE_ENUF' was not declared in this scope
 #define INFINITY   ((float)(_HUGE_ENUF * _HUGE_ENUF))
                             ^~~~~~~~~~
/usr/include/math.h:23:28: note: in expansion of macro 'INFINITY'
 #define HUGE_VAL  ((double)INFINITY)
                            ^~~~~~~~
tools/compilers/roqvq/codec.cpp:22:29: note: suggested alternative: 'HUGE_VALF'
 #define INFINITY   ((float)(_HUGE_ENUF * _HUGE_ENUF))
                             ^~~~~~~~~~
/usr/include/math.h:23:28: note: in expansion of macro 'INFINITY'
 #define HUGE_VAL  ((double)INFINITY)
                            ^~~~~~~~
tools/compilers/roqvq/codec.cpp: In member function 'void codec::SparseEncode()':
tools/compilers/roqvq/codec.cpp:1311:5: warning: this 'if' clause does not guard... [-Wmisleading-indentation]
     if (qStatus[i].status < DEAD) num[qStatus[i].status]++; j++;
     ^~
tools/compilers/roqvq/codec.cpp:1311:61: note: ...this statement, but the latter is misleadingly indented as if it were guarded by the 'if'
     if (qStatus[i].status < DEAD) num[qStatus[i].status]++; j++;
                                                             ^
tools/compilers/roqvq/codec.cpp:1319:5: warning: this 'if' clause does not guard... [-Wmisleading-indentation]
     if (qStatus[i].status < DEAD) num[qStatus[i].status]++; j++;
     ^~
tools/compilers/roqvq/codec.cpp:1319:61: note: ...this statement, but the latter is misleadingly indented as if it were guarded by the 'if'
     if (qStatus[i].status < DEAD) num[qStatus[i].status]++; j++;
                                                             ^
tools/compilers/roqvq/codec.cpp: In member function 'void codec::EncodeNothing()':
tools/compilers/roqvq/codec.cpp:1412:5: warning: this 'if' clause does not guard... [-Wmisleading-indentation]
     if (qStatus[i].status < DEAD) num[qStatus[i].status]++; j++;
     ^~
tools/compilers/roqvq/codec.cpp:1412:61: note: ...this statement, but the latter is misleadingly indented as if it were guarded by the 'if'
     if (qStatus[i].status < DEAD) num[qStatus[i].status]++; j++;
                                                             ^
tools/compilers/roqvq/codec.cpp:1420:5: warning: this 'if' clause does not guard... [-Wmisleading-indentation]
     if (qStatus[i].status < DEAD) num[qStatus[i].status]++; j++;
     ^~
tools/compilers/roqvq/codec.cpp:1420:61: note: ...this statement, but the latter is misleadingly indented as if it were guarded by the 'if'
     if (qStatus[i].status < DEAD) num[qStatus[i].status]++; j++;
                                                             ^
tools/compilers/roqvq/codec.cpp: In member function 'void codec::VQ(int, int, const unsigned char*, float*, double**, bool)':
tools/compilers/roqvq/codec.cpp:22:29: error: '_HUGE_ENUF' was not declared in this scope
 #define INFINITY   ((float)(_HUGE_ENUF * _HUGE_ENUF))
                             ^~~~~~~~~~
/usr/include/math.h:23:28: note: in expansion of macro 'INFINITY'
 #define HUGE_VAL  ((double)INFINITY)
                            ^~~~~~~~
tools/compilers/roqvq/codec.cpp:22:29: note: suggested alternative: 'HUGE_VALF'
 #define INFINITY   ((float)(_HUGE_ENUF * _HUGE_ENUF))
                             ^~~~~~~~~~
/usr/include/math.h:23:28: note: in expansion of macro 'INFINITY'
 #define HUGE_VAL  ((double)INFINITY)
                            ^~~~~~~~
g++ -o build/scons_x64/release/core/tools/compilers/roqvq/roq.o -c -pipe -Wall -Wno-unknown-pragmas -Wno-unused-variable -Wno-unused-but-set-variable -Wno-sign-compare -fmessage-length=0 -std=c++14 -fno-strict-aliasing -D_GLIBCXX_USE_CXX11_ABI=0 -fvisibility=hidden -m64 -g -O3 -ffast-math -fno-unsafe-math-optimizations -DXTHREADS -DExtLibs= -Ibuild/scons_x64/release/core/sys/scons -Isys/scons -IThirdParty/artefacts/zlib/include -IThirdParty/artefacts/libcurl/include -IThirdParty/artefacts/openal/include -IThirdParty/artefacts/ogg/include -IThirdParty/artefacts/vorbis/include -IThirdParty/artefacts/devil/include -IThirdParty/artefacts/libjpeg/include -IThirdParty/artefacts/ffmpeg/include -IThirdParty/artefacts/doctest/include -IThirdParty/artefacts/pugixml/include -Irenderer -I. -Iidlib -Iframework -Igame tools/compilers/roqvq/roq.cpp
scons: *** [build/scons_x64/release/core/tools/compilers/roqvq/codec.o] Error 1
In file included from idlib/../idlib/Lib.h:194,
                 from idlib/precompiled.h:107,
                 from tools/compilers/roqvq/roq.cpp:15:
idlib/../idlib/geometry/Surface.h: In constructor 'idSurface::idSurface(const idDrawVert*, int, const int*, int)':
idlib/../idlib/geometry/Surface.h:109:66: warning: 'void* memcpy(void*, const void*, size_t)' writing to an object of type 'class idDrawVert' with no trivial copy-assignment; use copy-assignment or copy-initialization instead [-Wclass-memaccess]
  memcpy( this->verts.Ptr(), verts, numVerts * sizeof( verts[0] ) );
                                                                  ^
In file included from idlib/../idlib/Lib.h:190,
                 from idlib/precompiled.h:107,
                 from tools/compilers/roqvq/roq.cpp:15:
idlib/../idlib/geometry/DrawVert.h:27:7: note: 'class idDrawVert' declared here
 class idDrawVert {
       ^~~~~~~~~~
scons: building terminated because of errors.

**Comment by cizra** [comment]
Are you trying to play around with GITification of Darkmod, or are you just
trying to get Darkmod to run?

In the 1st case - I rewrote some history to get rid of larger files that
don't really belong to the Git repo. This left the build in a broken state,
because now the dependencies aren't fetched from anywhere.

In the 2nd case, perhaps consider fetching the source from the official
repository?

**Comment by sodomon2** [comment]
OK I already did but now you tell me 
Whoops! That unsubscribe link isn't valid for your account.

**Comment by sodomon2** [comment]
I already cloned the official repository with svn but ma gives the same error

**Comment by cizra** [comment]
Hm, incompatible version of GCC perhaps?
Anyway, I'm not really qualified to give support on compiling Darkmod.
You're likely to get better support at
http://forums.thedarkmod.com/index.php?/forum/58-tdm-tech-support/
